# Generated by Django 2.2.3 on 2019-07-17 02:23

from django.db import migrations, models
import django.db.models.deletion
import flowapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StepType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('url_validation', models.CharField(choices=[('D', 'Disallowed'), ('A', 'Allowed'), ('R', 'Required')], default='ALLOWED', max_length=1)),
                ('has_verification', models.CharField(choices=[('D', 'Disallowed'), ('A', 'Allowed'), ('R', 'Required')], default='ALLOWED', max_length=1)),
                ('has_fixture', models.CharField(choices=[('D', 'Disallowed'), ('A', 'Allowed'), ('R', 'Required')], default='ALLOWED', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.CharField(default=flowapp.models.truncated_uuid, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('passed', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.CharField(default=flowapp.models.truncated_uuid, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=1)),
                ('desired_result', models.CharField(blank=True, max_length=500, null=True)),
                ('passed', models.BooleanField(blank=True, default=False, null=True)),
                ('has_fixture', models.BooleanField(default=False)),
                ('fixture_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.Flow')),
                ('step_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flowapp.StepType')),
            ],
            options={
                'ordering': ['order'],
                'index_together': {('flow', 'order')},
            },
        ),
    ]
