# Generated by Django 2.2.3 on 2019-07-09 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.FloatField()),
                ('desired_result', models.CharField(blank=True, max_length=500, null=True)),
                ('passed', models.BooleanField(blank=True, default=False, null=True)),
                ('fixture_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowapp.Flow')),
            ],
        ),
        migrations.CreateModel(
            name='StepType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('Action', (('load_url', 'Load URL'), ('click_on', 'Click On'), ('enter', 'Enter In'), ('set', 'Set'))), ('Verification', 'Verification')], max_length=15)),
                ('has_fixture', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='ActionTypes',
        ),
        migrations.AddField(
            model_name='step',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flowapp.StepType'),
        ),
    ]
