# Generated by Django 2.2.3 on 2019-07-09 19:36

from django.db import migrations, models
import flowapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('flowapp', '0002_auto_20190709_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='type',
            field=models.CharField(choices=[('load_url', 'Load URL'), ('click_on', 'Click On'), ('', 'Enter In'), ('set', 'Set'), ('verification', 'Verification')], max_length=100, verbose_name=flowapp.models.StepType),
        ),
        migrations.AlterField(
            model_name='steptype',
            name='step_type',
            field=models.CharField(choices=[('load_url', 'Load URL'), ('click_on', 'Click On'), ('', 'Enter In'), ('set', 'Set'), ('verification', 'Verification')], max_length=15),
        ),
    ]
