# Generated by Django 2.2.3 on 2019-07-09 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowapp', '0003_auto_20190709_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flowapp.StepType'),
        ),
    ]
