# Generated by Django 2.2.3 on 2019-07-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowapp', '0004_auto_20190709_1940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoadURL',
        ),
        migrations.AlterField(
            model_name='steptype',
            name='step_type',
            field=models.CharField(choices=[('load_url', 'Load URL'), ('click_on', 'Click On'), ('enter_in', 'Enter In'), ('set', 'Set'), ('verification', 'Verification')], max_length=15),
        ),
    ]
